name: calendar


on:
  schedule:
    # - cron: 0 0,12 * * * # JST
    # - cron: 15 3,9,15,21 * * * # UTC
# クーロン一時停止中
#    - cron: 30 1,3,5,7,9,11,13,15,17,19,21,23 * * * # UTC
  push:
    branches:
      - master

jobs:
  fetch-calendar:
    name: fetch calendar
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -y pngquant advancecomp
      - name: mkdir
        run: mkdir public
      - name: fetch calendar image
        run: |
          curl -L -o public/calendar.png "http://drive.google.com/uc?export=view&id=1P2upt9HdnDLLMrEff8GJPDp3ig-IDXc6"
          curl -L -o public/quest-calendar.png "http://drive.google.com/uc?export=view&id=1Ra0LRkvjbzdzCe_nGtnzzGlKOobVncUr"
      - name: check format
        run: |
          [ `file --brief --mime-type public/calendar.png` = "image/png" ]
          [ `file --brief --mime-type public/quest-calendar.png` = "image/png" ]
      - name: optimize
        run: |
          pngquant --force --ext .png --speed 1 public/calendar.png
          advpng -z -4 -i 10 public/calendar.png
          pngquant --force --ext .png --speed 1 public/quest-calendar.png
          advpng -z -4 -i 10 public/quest-calendar.png
      - name: cname
        run: echo calendar.teruaki-tsubokura.com > public/CNAME
      - name: gh-pages
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public
